# Generated by Django 4.0 on 2021-12-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summery',
            field=models.TextField(null=True),
        ),
    ]
