# Generated by Django 3.2 on 2022-01-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_summery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'permissions': [('can_publish', 'Can publish a blog')]},
        ),
    ]
